name: future_of_data
description: ''
version: '1.1'
author: maciej+demo7@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: futureofdata
  parentArtefactID: maciejdemos
  buildSystem: wheel
  author: null
  createdAt: '2024-01-25 15:04:57'
pipelines:
  pipelines/customers:
    name: customers
    description: ''
    author: maciej+demo7@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-01-25 15:04:57'
    datasets:
      inputs:
      - datasets/customers_raw
      outputs:
      - datasets/customers
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customers_raw:
    name: customers_raw
    description: ''
    author: maciej+demo7@prophecy.io
    createdAt: '2024-01-25 15:20:12'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 8875
        datasetType: File
        description: ''
        author: maciej+demo7@prophecy.io
        createdAt: '2024-01-25 15:20:12'
  datasets/customers:
    name: customers
    description: ''
    author: maciej+demo7@prophecy.io
    createdAt: '2024-01-25 15:21:08'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 8875
        datasetType: Database
        description: ''
        author: maciej+demo7@prophecy.io
        createdAt: '2024-01-25 15:21:08'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-01-25 15:04:57'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.1.2
    isDefault: true
    author: null
    createdAt: '2024-01-25 15:04:41'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2024-01-25 15:04:41'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
