name: future_of_data
description: ''
version: '1.2'
author: maciej+demo7@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: futureofdata
  parentArtefactID: maciejdemos
  buildSystem: wheel
  author: null
  createdAt: '2024-01-25 15:04:57'
pipelines:
  pipelines/customers:
    name: customers
    description: ''
    author: maciej+demo7@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-01-25 15:04:57'
    datasets:
      inputs:
      - datasets/customers_raw
      outputs:
      - datasets/customers
    subgraphs: []
    dependencies: {}
  pipelines/orders:
    name: orders
    description: ''
    author: maciej+demo7@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-02-13 20:07:29'
    datasets:
      inputs:
      - datasets/orders_raw
      outputs:
      - datasets/orders
    subgraphs: []
    dependencies: {}
  pipelines/customers_orders:
    name: customers_orders
    description: ''
    author: maciej+demo7@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-02-13 20:18:50'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customers_raw:
    name: customers_raw
    description: ''
    author: maciej+demo7@prophecy.io
    createdAt: '2024-01-25 15:20:12'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 8875
        datasetType: File
        description: ''
        author: maciej+demo7@prophecy.io
        createdAt: '2024-01-25 15:20:12'
  datasets/customers:
    name: customers
    description: ''
    author: maciej+demo7@prophecy.io
    createdAt: '2024-01-25 15:21:08'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 8875
        datasetType: Database
        description: ''
        author: maciej+demo7@prophecy.io
        createdAt: '2024-01-25 15:21:08'
  datasets/orders_raw:
    name: orders_raw
    description: ''
    author: maciej+demo7@prophecy.io
    createdAt: '2024-02-13 20:13:10'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 8875
        datasetType: File
        description: ''
        author: maciej+demo7@prophecy.io
        createdAt: '2024-02-13 20:13:10'
  datasets/orders:
    name: orders
    description: ''
    author: maciej+demo7@prophecy.io
    createdAt: '2024-02-13 20:14:43'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 8875
        datasetType: Database
        description: ''
        author: maciej+demo7@prophecy.io
        createdAt: '2024-02-13 20:14:43'
templates: {}
jobs:
  jobs/monthly_schedule:
    name: monthly_schedule
    description: ''
    fabricUID: 8875
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: maciej@prophecy.io
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/customers_orders
    - pipelines/customers
    - pipelines/orders
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-02-13 20:32:58'
    author: maciej+demo7@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-01-25 15:04:57'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.3
    isDefault: true
    author: null
    createdAt: '2024-02-13 17:29:03'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2024-01-25 15:04:41'
  '19866':
    projectUID: 19866
    projectName: data_enrichment
    repositoryPath: gitUri=http://gitserver:3000/j10EL0W3_team_6825/KcFBQ9ZA_project_19866.git&subPath=
    version: data_enrichment/1.1
    isDefault: false
    author: null
    createdAt: '2024-02-13 20:27:09'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
