from .customers_orders import customers_orders
from .total_spent_by_customer import total_spent_by_customer
from .customers import customers
from .by_total_spent_desc_nulls_first import by_total_spent_desc_nulls_first
from .limit_50_customer_details import limit_50_customer_details
from .customer_order_amount import customer_order_amount
from .limit_50 import limit_50
from .orders import orders